name: estate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_ui_auth: ^1.16.0
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  logger: ^2.4.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  form_builder_image_picker: ^4.1.0
  flutter_map: ^7.0.2
  location: ^7.0.1
  latlong2: ^0.9.1
  gap: ^3.0.1
  refena_flutter: ^2.1.1
  whatsapp_unilink: ^2.1.0
  form_builder_file_picker: ^4.2.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.1
  flutter_map_animations: ^0.7.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_map_cache: ^1.5.1
  dio_cache_interceptor_hive_store: ^3.2.2
  path_provider: ^2.1.4
  easy_image_viewer: ^1.5.1
  form_builder_extra_fields: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
